### ISSUE TITLE
Update of my contribution, incl affiliation

### ISSUE THREAD

**Issue by meneer** [IDPros/anno-biblio#36]
My data...
My affiliation should be changed:
André Koot is is principal consultant at SonicBee BV in Amsterdam, The Netherlands

Nist 800-207, https://csrc.nist.gov/publications/detail/sp/800-207/final
This paper is a great introduction to the world of Zero Trust computing. It is the first source explicitly adding the concept of policy based access control (known from XACML and ABAC) to the common network oriented zero trust infrastructure. The document shows multiple reference implementations of the zero trust models.
It's not only a very good explanation of the concept, but it's also an easy read. An essential standard work for future access control developments.

**Comment by hlflanagan** [comment]
Your affiliation has been updated and your contribution of 800-207 has been added. Thank you!
